/* Autogenerated by /usr/bin/halcompile on Mon Apr 27 15:07:11 2026 -- do not edit */
#include "rtapi.h"
#ifdef RTAPI
#include "rtapi_app.h"
#endif
#include "rtapi_string.h"
#include "rtapi_errno.h"
#include "hal.h"
#include "rtapi_math64.h"

static int comp_id;

#ifdef MODULE_INFO
MODULE_INFO(linuxcnc, "component:wj200_vfd:Hitachi wj200 modbus driver");
MODULE_INFO(linuxcnc, "param:mbslaveaddr:u32:0:rw:Modbus slave address:None:None");
MODULE_INFO(linuxcnc, "param:frequency_scale:float:0:rw:RPM / frequency, default 1:1:None");
MODULE_INFO(linuxcnc, "pin:commanded_frequency:float:0:in:Frequency of vfd (scaled to RPM):None:None");
MODULE_INFO(linuxcnc, "pin:motor_frequency:float:0:out:Motor's actual frequency (scaled to RPM):None:None");
MODULE_INFO(linuxcnc, "pin:motor_reverse:bit:0:out:1 when actually turning in reverse:None:None");
MODULE_INFO(linuxcnc, "pin:reverse:bit:0:in:1 when reverse 0 when forward:None:None");
MODULE_INFO(linuxcnc, "pin:run:bit:0:in:run the vfd:None:None");
MODULE_INFO(linuxcnc, "pin:enable:bit:0:in:1 to enable the vfd. 0 will remote trip the vfd, thereby disabling it.:None:None");
MODULE_INFO(linuxcnc, "pin:is_running:bit:0:out:1 when running:None:None");
MODULE_INFO(linuxcnc, "pin:is_at_speed:bit:0:out:1 when running at assigned frequency:None:None");
MODULE_INFO(linuxcnc, "pin:is_stopped:bit:0:out:1 when stopped:None:None");
MODULE_INFO(linuxcnc, "pin:is_ready:bit:0:out:1 when vfd is ready to run:None:None");
MODULE_INFO(linuxcnc, "pin:is_alarm:bit:0:out:1 when vfd alarm is set:None:None");
MODULE_INFO(linuxcnc, "pin:motor_current:float:0:out:Output current in amps:None:None");
MODULE_INFO(linuxcnc, "pin:motor_voltage:float:0:out:Output voltage in volts:None:None");
MODULE_INFO(linuxcnc, "pin:motor_power:float:0:out:Output power in kilowatts (register 0x1012, kW*10):None:None");
MODULE_INFO(linuxcnc, "pin:heatsink_temp:float:0:out:Temperature of drive heatsink:None:None");
MODULE_INFO(linuxcnc, "pin:modbus_errors:u32:0:out:Cumulative count of Modbus communication errors:None:None");
MODULE_INFO(linuxcnc, "pin:watchdog_out:bit:0:out:Alternates between 1 and 0 after every update cycle. Feed into a watchdog component to ensure vfd driver is communicating with the vfd properly.:None:None");
MODULE_INFO(linuxcnc, "license:GPLv2 or greater");
MODULE_LICENSE("GPLv2 or greater");
#endif // MODULE_INFO


struct __comp_state {
    struct __comp_state *_next;
    hal_float_t *commanded_frequency;
    hal_float_t *motor_frequency;
    hal_bit_t *motor_reverse;
    hal_bit_t *reverse;
    hal_bit_t *run;
    hal_bit_t *enable;
    hal_bit_t *is_running;
    hal_bit_t *is_at_speed;
    hal_bit_t *is_stopped;
    hal_bit_t *is_ready;
    hal_bit_t *is_alarm;
    hal_float_t *motor_current;
    hal_float_t *motor_voltage;
    hal_float_t *motor_power;
    hal_float_t *heatsink_temp;
    hal_u32_t *modbus_errors;
    hal_bit_t *watchdog_out;
    hal_u32_t mbslaveaddr;
    hal_float_t frequency_scale;
};
#include <stdlib.h>
struct __comp_state *__comp_first_inst=0, *__comp_last_inst=0;

static int __comp_get_data_size(void);
#undef TRUE
#define TRUE (1)
#undef FALSE
#define FALSE (0)
#undef true
#define true (1)
#undef false
#define false (0)

static int export(char *prefix, long extra_arg) {
    int r = 0;
    int sz = sizeof(struct __comp_state) + __comp_get_data_size();
    struct __comp_state *inst = hal_malloc(sz);
    memset(inst, 0, sz);
    r = hal_pin_float_newf(HAL_IN, &(inst->commanded_frequency), comp_id,
        "%s.commanded-frequency", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->motor_frequency), comp_id,
        "%s.motor-frequency", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->motor_reverse), comp_id,
        "%s.motor-reverse", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_IN, &(inst->reverse), comp_id,
        "%s.reverse", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_IN, &(inst->run), comp_id,
        "%s.run", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_IN, &(inst->enable), comp_id,
        "%s.enable", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->is_running), comp_id,
        "%s.is-running", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->is_at_speed), comp_id,
        "%s.is-at-speed", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->is_stopped), comp_id,
        "%s.is-stopped", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->is_ready), comp_id,
        "%s.is-ready", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->is_alarm), comp_id,
        "%s.is-alarm", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->motor_current), comp_id,
        "%s.motor-current", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->motor_voltage), comp_id,
        "%s.motor-voltage", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->motor_power), comp_id,
        "%s.motor-power", prefix);
    if(r != 0) return r;
    r = hal_pin_float_newf(HAL_OUT, &(inst->heatsink_temp), comp_id,
        "%s.heatsink-temp", prefix);
    if(r != 0) return r;
    r = hal_pin_u32_newf(HAL_OUT, &(inst->modbus_errors), comp_id,
        "%s.modbus-errors", prefix);
    if(r != 0) return r;
    r = hal_pin_bit_newf(HAL_OUT, &(inst->watchdog_out), comp_id,
        "%s.watchdog-out", prefix);
    if(r != 0) return r;
    r = hal_param_u32_newf(HAL_RW, &(inst->mbslaveaddr), comp_id,
        "%s.mbslaveaddr", prefix);
    if(r != 0) return r;
    r = hal_param_float_newf(HAL_RW, &(inst->frequency_scale), comp_id,
        "%s.frequency-scale", prefix);
    inst->frequency_scale = 1;
    if(r != 0) return r;
    if(__comp_last_inst) __comp_last_inst->_next = inst;
    __comp_last_inst = inst;
    if(!__comp_first_inst) __comp_first_inst = inst;
    return 0;
}
static int default_count=1, count=0;
char *names[16] = {0,};
int rtapi_app_main(void) {
    int r = 0;
    int i;
    comp_id = hal_init("wj200_vfd");
    if(comp_id < 0) return comp_id;
    if(count && names[0]) {
        rtapi_print_msg(RTAPI_MSG_ERR,"count= and names= are mutually exclusive\n");
        return -EINVAL;
    }
    if(!count && !names[0]) count = default_count;
    if(count) {
        for(i=0; i<count; i++) {
            char buf[HAL_NAME_LEN + 1];
            rtapi_snprintf(buf, sizeof(buf), "wj200-vfd.%d", i);
            r = export(buf, i);
            if(r != 0) break;
       }
    } else {
        int max_names = sizeof(names)/sizeof(names[0]);
        for(i=0; (i < max_names) && names[i]; i++) {
            if (strlen(names[i]) < 1) {
                rtapi_print_msg(RTAPI_MSG_ERR, "names[%d] is invalid (empty string)\n", i);
                r = -EINVAL;
                break;
            }
            r = export(names[i], i);
            if(r != 0) break;
       }
    }
    if(r) {
        hal_exit(comp_id);
    } else {
        hal_ready(comp_id);
    }
    return r;
}

void rtapi_app_exit(void) {
    hal_exit(comp_id);
}
static void user_mainloop(void);
static void userinit(int argc, char **argv);

int __comp_parse_count(int *argc, char **argv) {
    int i;
    for (i = 0; i < *argc; i ++) {
        if (strncmp(argv[i], "count=", 6) == 0) {
            errno = 0;
            count = strtoul(&argv[i][6], NULL, 0);
            for (; i+1 < *argc; i ++) {
                argv[i] = argv[i+1];
            }
            argv[i] = NULL;
            (*argc)--;
            if (errno == 0) {
                return 1;
            }
        }
    }
    return 0;
}


int __comp_parse_names(int *argc, char **argv) {
    int i;
    for (i = 0; i < *argc; i ++) {
        if (strncmp(argv[i], "names=", 6) == 0) {
            char *p = &argv[i][6];
            int j;
            for (; i+1 < *argc; i ++) {
                argv[i] = argv[i+1];
            }
            argv[i] = NULL;
            (*argc)--;
            for (j = 0; j < 16; j ++) {
                names[j] = strtok(p, ",");
                p = NULL;
                if (names[j] == NULL) {
                    return 1;
                }
            }
            return 1;
        }
    }
    return 0;
}

int argc=0; char **argv=0;
int main(int argc_, char **argv_) {
    argc = argc_; argv = argv_;
    int found_count, found_names;
    found_count = __comp_parse_count(&argc, argv);
    found_names = __comp_parse_names(&argc, argv);
    if (found_count && found_names) {
        rtapi_print_msg(RTAPI_MSG_ERR, "count= and names= are mutually exclusive\n");
        return 1;
    }
    userinit(argc, argv);

    if(rtapi_app_main() < 0) return 1;
    user_mainloop();
    rtapi_app_exit();
    return 0;
}

#undef FUNCTION
#define FUNCTION(name) static void name(struct __comp_state *__comp_inst, long period)
#undef EXTRA_SETUP
#define EXTRA_SETUP() static int extra_setup(struct __comp_state *__comp_inst, char *prefix, long extra_arg)
#undef EXTRA_CLEANUP
#define EXTRA_CLEANUP() static void extra_cleanup(void)
#undef fperiod
#define fperiod (period * 1e-9)
#undef commanded_frequency
#define commanded_frequency (0+*__comp_inst->commanded_frequency)
#undef motor_frequency
#define motor_frequency (*__comp_inst->motor_frequency)
#undef motor_reverse
#define motor_reverse (*__comp_inst->motor_reverse)
#undef reverse
#define reverse (0+*__comp_inst->reverse)
#undef run
#define run (0+*__comp_inst->run)
#undef enable
#define enable (0+*__comp_inst->enable)
#undef is_running
#define is_running (*__comp_inst->is_running)
#undef is_at_speed
#define is_at_speed (*__comp_inst->is_at_speed)
#undef is_stopped
#define is_stopped (*__comp_inst->is_stopped)
#undef is_ready
#define is_ready (*__comp_inst->is_ready)
#undef is_alarm
#define is_alarm (*__comp_inst->is_alarm)
#undef motor_current
#define motor_current (*__comp_inst->motor_current)
#undef motor_voltage
#define motor_voltage (*__comp_inst->motor_voltage)
#undef motor_power
#define motor_power (*__comp_inst->motor_power)
#undef heatsink_temp
#define heatsink_temp (*__comp_inst->heatsink_temp)
#undef modbus_errors
#define modbus_errors (*__comp_inst->modbus_errors)
#undef watchdog_out
#define watchdog_out (*__comp_inst->watchdog_out)
#undef mbslaveaddr
#define mbslaveaddr (__comp_inst->mbslaveaddr)
#undef frequency_scale
#define frequency_scale (__comp_inst->frequency_scale)
#undef FOR_ALL_INSTS
#define FOR_ALL_INSTS() struct __comp_state *__comp_inst; for(__comp_inst = __comp_first_inst; __comp_inst; __comp_inst = __comp_inst->_next)


#line 25 "wj200_vfd.comp"
/*
  Userspace HAL component to control a Hitatchi WJ200 series VFD

  Written by Curtis Dutton, inspired by vfs11_vfd.c in linuxcnc

  Copyright (C) 2012 Curtis Dutton, OK Computers LLC

  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation, version 2.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301-1307  USA.

  see 'man wj200_vfd' and the WJ200 section in the Drivers manual.

  Register map (from official WJ200 manual, page B-30):
    0x1001/0x1002  Output frequency monitor  (Hz * 100)
    0x1003         Output current monitor    (A * 100)
    0x1004         Rotation direction        (0=stop, 1=fwd, 2=rev)
    0x1011         Output voltage monitor    (V * 10)
    0x1012         Power monitor             (kW * 10)
    0x1019         Heatsink temperature      (C * 10)
*/
#include<stdio.h>
#include<errno.h>
#include<getopt.h>
#include<stdbool.h>
#include<math.h>
#include<modbus.h>
#include<unistd.h>
#include<ctype.h>
#include<signal.h>

typedef struct
{
        uint8_t running;
        uint8_t ready;
        uint8_t direction;
        uint8_t at_speed;
        uint8_t alarm;
	float output_current;
	float output_voltage;
	float output_power;
	uint16_t output_rotation;
	float sink_temp;
        uint16_t frequency;
        uint8_t stopped;
	float actual_frequency;
} wj200_status;

/* Global context pointer for signal handler */
modbus_t *ctx = NULL;
volatile sig_atomic_t do_exit = 0;

/* Signal handler: stop VFD cleanly before exit */
void shutdown_handler(int sig)
{
	(void)sig;
	do_exit = 1;
}

/*sets the operating frequency of the vfd*/
bool wj200_setFrequency(modbus_t* ctx, uint16_t frequency)
{
        return modbus_write_registers(ctx, 0x001, 1, &frequency) > 0;
}

/*resets the trip status of the VFD*/
bool wj200_reset(modbus_t* ctx)
{
        /*after the reset, the wj200 vfd seem to need a second
        before it will reply to more modbus commands*/
        int rc = modbus_write_bit(ctx, 0x003, TRUE);

        sleep(1);

        return rc > 0;
}

bool wj200_setDirection(modbus_t* ctx, bool direction)
{
	return modbus_write_bit(ctx, 0x001, direction) > 0;
}

bool wj200_trip(modbus_t* ctx)
{
        return modbus_write_bit(ctx, 0x002, TRUE) > 0;
}

bool wj200_run(modbus_t* ctx, bool runBit)
{
        return modbus_write_bit(ctx, 0x000, runBit) > 0;
}


bool wj200_getStatus(modbus_t* ctx, wj200_status* status)
{
        int rc;
        uint8_t bits[16];
        uint8_t bits2[16];
        uint16_t registers[2];
	uint16_t currentRegister[2];
	uint16_t temperatureRegister[1];
	uint16_t actualFreq[2];
	uint16_t voltageRegister[1];
	uint16_t powerRegister[1];

        /*read coils 0x000F thru 0x0019 in one step*/
        rc = modbus_read_bits(ctx, 0x000F-1, 11, bits);

        if(rc < 0)
        {
                return false;
        }

        /*read coil 0x0028 in one step*/
        rc = modbus_read_bits(ctx, 0x0028-1, 1, bits2);

        if(rc < 0)
        {
                return false;
        }

        /*read the first 2 registers*/
        rc = modbus_read_registers(ctx, 0x000, 2, registers);

        if(rc < 0)
        {
                return false;
        }

	/* Read 0x1003 (output current), 0x1004 (output rotation) */
        rc = modbus_read_registers(ctx, 0x1003-1, 2, currentRegister);

        if(rc < 0)
        {
                return false;
        }

	rc = modbus_read_registers(ctx, 0x1019-1, 1, temperatureRegister);

        if(rc < 0)
        {
                return false;
        }

	/* Read output voltage from register 0x1011 (V * 10)
	   NON-FATAL: if register unavailable, voltage stays 0 */
	rc = modbus_read_registers(ctx, 0x1011-1, 1, voltageRegister);
	if(rc > 0) {
		status->output_voltage = voltageRegister[0];
	} else {
		status->output_voltage = 0;
	}

	/* Read output power from register 0x1012 (kW * 10)
	   NON-FATAL: if register unavailable, power stays 0 */
	rc = modbus_read_registers(ctx, 0x1012-1, 1, powerRegister);
	if(rc > 0) {
		status->output_power = powerRegister[0];
	} else {
		status->output_power = 0;
	}

	/* 0x100B Available when P003 = 1 (encoder-based feedback) */
	rc = modbus_read_registers(ctx, 0x1001-1, 2, actualFreq);

        if(rc < 0)
        {
                return false;
        }

        status->running = bits[0];
        status->direction = bits[1];
        status->ready = bits[2];
        status->alarm = bits[9];
        status->at_speed = bits[5];
        status->frequency = registers[1];
	status->output_current = currentRegister[0];
	status->output_rotation = currentRegister[1];
	status->sink_temp = temperatureRegister[0];
        status->stopped = bits2[0];
	status->actual_frequency = (actualFreq[0] * 65536 + actualFreq[1]) / 100.0;

        return true;
}

void print_modbus_error(struct __comp_state *__comp_inst, const char* msg)
{
	fprintf(stderr,
		"Error: wj200_vfd slave(%u): %s - Modbus error (%d) -  %s\n",
		mbslaveaddr,
		msg,
		errno,
		modbus_strerror(errno));
}


/* modbus connection settings*/
char *device = "/dev/ttyS0";
int baud = 9600;
char parity = 'N';
int data_bits = 8;
int stop_bits = 1;

void userinit(int argc, char **argv)
{
	int opt_index = 0;
	int c = 0;

	/* Register signal handlers for clean VFD shutdown */
	signal(SIGTERM, shutdown_handler);
	signal(SIGINT,  shutdown_handler);

	static struct option options[] = {
		{"baud",   required_argument, 0, 0 },
		{"parity", required_argument, 0, 0 },
		{"databits", required_argument, 0, 0 },
		{"stopbits", required_argument, 0, 0 },
		{"device", required_argument, 0, 0 },
		{0, 0, 0, 0}
	};

	while(1) {
		c = getopt_long(argc, argv, "", options, &opt_index);

		if(c == -1)
			break;

		switch(opt_index) {
			case 0:
				baud = atoi(optarg);

				if(baud == 0)
				{
					fprintf(stderr,
						"Invalid argument: baud must be a number. Given '%s'\n",
						optarg);
					exit(1);
				}
				break;

			case 1:
				parity = toupper(optarg[0]);

				if(parity != 'E' && parity != 'O' && parity != 'N')
				{
					fprintf(stderr, 
						"Invalid argument: parity must be 'e', 'o' or 'n'. Given '%s'\n", 
						optarg);
					exit(1);
				}
				break;

			case 2:
				data_bits = atoi(optarg);

				if(data_bits == 0)
				{
					fprintf(stderr,
						"Invalid argument: databits must be a number. Given '%s'\n",
						optarg);
					exit(1);
				}
				break;

			case 3:
				stop_bits = atoi(optarg);

				if(stop_bits == 0)
				{
					fprintf(stderr,
						"Invalid argument: stopbits must be a number. Given '%s'\n",
						optarg);
					exit(1);
				}
				break;
			case 4:
				device = optarg;
				break;

			default:
                                fprintf(stderr, "internal error: invalid option index!\n");
				exit(1);
		}

	}

        if (optind < argc) {
            fprintf(stderr, "WARNING: unhandled arguments to wj200_vfd driver:\n");
            for (int i = optind; i < argc; i ++) {
                fprintf(stderr, "    %s\n", argv[i]);
            }
        }

	ctx = modbus_new_rtu(device, baud, parity, data_bits, stop_bits);

	if (ctx == NULL) {
		fprintf(stderr,
			"ERROR: wj200_vfd unable to create libmodbus context. - %s\n",
			modbus_strerror(errno));
		fprintf(stderr, "Check your commandline!\n");
		exit(1);
	}

	if (modbus_connect(ctx)) {
		fprintf(stderr,
			"ERROR: wj200_vfd unable to create libmodbus connection. - %s\n",
			modbus_strerror(errno));
		exit(1);
	}
}

void user_mainloop(void) {
	wj200_status status;
	uint16_t calculated_frequency;
        bool last_enable_state = FALSE;

	while(1) {

		/* Clean shutdown on SIGTERM or SIGINT (Ctrl+C):
		   Stop VFD before exit so it doesn't stay in run state */
		if(do_exit) {
			if(ctx) {
				FOR_ALL_INSTS() {
					if(mbslaveaddr != 0) {
						modbus_set_slave(ctx, mbslaveaddr);
						wj200_run(ctx, false);
					}
				}
				modbus_close(ctx);
				modbus_free(ctx);
			}
			exit(0);
		}

	FOR_ALL_INSTS() {
		if(mbslaveaddr == 0) {
			sleep(1);
			continue;
		}

		modbus_set_slave(ctx, mbslaveaddr);

                if(!wj200_getStatus(ctx, &status)) {
                    if (last_enable_state != enable) {
                        print_modbus_error(__comp_inst, "failed to get status");
                    }
                    last_enable_state = enable;
                    modbus_errors++;
                    continue;
                }

		is_running = status.running;
		is_ready = status.ready;
		is_alarm = status.alarm;
		is_stopped = status.stopped;
		motor_frequency = status.actual_frequency * frequency_scale;
		motor_reverse = status.output_rotation == 2;

		/* The WJ200 has a "bug" in that is_at_speed is set
		even if it's running in the wrong direction, which is
		not what we want.  Check that here.  */
		if (reverse == motor_reverse)
		  is_at_speed = (status.frequency == 0
		  	      ? status.stopped : status.at_speed);
		else
		  is_at_speed = 0;

		if(!status.alarm && !enable && !wj200_trip(ctx)) {
			print_modbus_error(__comp_inst, "failed to trip");
			modbus_errors++;
			continue;
		}
		else if(status.alarm && enable && !wj200_reset(ctx)) {
			print_modbus_error(__comp_inst, "failed to reset");
			modbus_errors++;
			continue;
		}
		else {
			calculated_frequency = (uint16_t)(fabs(commanded_frequency / frequency_scale) * 100);

			if(calculated_frequency != status.frequency
			   && !wj200_setFrequency(ctx, calculated_frequency)) {
				print_modbus_error(__comp_inst, "failed to set frequency");
				modbus_errors++;
				continue;
			}

			if(reverse != status.direction && !wj200_setDirection(ctx, reverse)) {
				print_modbus_error(__comp_inst, "failed to set direction");
				modbus_errors++;
				continue;
			}

			if(status.running ^ run && !wj200_run(ctx, run)) {
				print_modbus_error(__comp_inst, "failed to run");
				modbus_errors++;
				continue;
			}

			watchdog_out = !watchdog_out;
			motor_current = status.output_current / 100;
			motor_voltage = status.output_voltage / 10.0;
			motor_power   = status.output_power / 10.0;
			heatsink_temp = status.sink_temp / 10;
		}
	}
	}
}

static int __comp_get_data_size(void) { return 0; }
